In [85]:
import pandas as pd
import numpy as np

raw_df = pd.read_csv('dataset/googleplaystore.csv')
raw_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [86]:
# Get the number of rows with invalid ratings (5 < Rating and NaN)
greater_than_five = raw_df[raw_df['Rating'] > 5]
less_than_1 = raw_df[raw_df['Rating'] < 1]
is_nan = raw_df[raw_df['Rating'].isnull()]
is_string = raw_df[raw_df['Rating'].apply(lambda x: isinstance(x, str))]

print(f"Number of rows with rating greater than 5: {len(greater_than_five)}")
print(f"Number of rows with rating less than 1: {len(less_than_1)}")
print(f"Number of rows with NaN rating: {len(is_nan)}")
print(f"Number of rows with string rating: {len(is_string)}")

Number of rows with rating greater than 5: 1
Number of rows with rating less than 1: 0
Number of rows with NaN rating: 1474
Number of rows with string rating: 0

In [87]:
# Get frequency of each category
category_counts = raw_df['Category'].value_counts()
category_counts

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [88]:
genre_counts = raw_df['Genres'].unique()
for genre in genre_counts:
    print(genre)

Art & Design
Art & Design;Pretend Play
Art & Design;Creativity
Art & Design;Action & Adventure
Auto & Vehicles
Beauty
Books & Reference
Business
Comics
Comics;Creativity
Communication
Dating
Education;Education
Education
Education;Creativity
Education;Music & Video
Education;Action & Adventure
Education;Pretend Play
Education;Brain Games
Entertainment
Entertainment;Music & Video
Entertainment;Brain Games
Entertainment;Creativity
Events
Finance
Food & Drink
Health & Fitness
House & Home
Libraries & Demo
Lifestyle
Lifestyle;Pretend Play
Adventure;Action & Adventure
Arcade
Casual
Card
Casual;Pretend Play
Action
Strategy
Puzzle
Sports
Music
Word
Racing
Casual;Creativity
Casual;Action & Adventure
Simulation
Adventure
Board
Trivia
Role Playing
Simulation;Education
Action;Action & Adventure
Casual;Brain Games
Simulation;Action & Adventure
Educational;Creativity
Puzzle;Brain Games
Educational;Education
Card;Brain Games
Educational;Brain Games
Educational;Pretend Play
Entertainment;Education
Casual;Education
Music;Music & Video
Racing;Action & Adventure
Arcade;Pretend Play
Role Playing;Action & Adventure
Simulation;Pretend Play
Puzzle;Creativity
Sports;Action & Adventure
Educational;Action & Adventure
Arcade;Action & Adventure
Entertainment;Action & Adventure
Puzzle;Action & Adventure
Strategy;Action & Adventure
Music & Audio;Music & Video
Health & Fitness;Education
Adventure;Education
Board;Brain Games
Board;Action & Adventure
Board;Pretend Play
Casual;Music & Video
Role Playing;Pretend Play
Entertainment;Pretend Play
Video Players & Editors;Creativity
Card;Action & Adventure
Medical
Social
Shopping
Photography
Travel & Local
Travel & Local;Action & Adventure
Tools
Tools;Education
Personalization
Productivity
Parenting
Parenting;Music & Video
Parenting;Education
Parenting;Brain Games
Weather
Video Players & Editors
Video Players & Editors;Music & Video
News & Magazines
Maps & Navigation
Health & Fitness;Action & Adventure
Educational
Casino
Adventure;Brain Games
Trivia;Education
Lifestyle;Education
Books & Reference;Creativity
Books & Reference;Education
Puzzle;Education
Role Playing;Education
Role Playing;Brain Games
Strategy;Education
Racing;Pretend Play
Communication;Creativity
February 11, 2018
Strategy;Creativity

In [89]:
price_counts = raw_df['Price'].value_counts()
print(price_counts)

Price
0           10040
$0.99         148
$2.99         129
$1.99          73
$4.99          72
            ...
$394.99         1
$1.26           1
Everyone        1
$1.20           1
$1.04           1
Name: count, Length: 93, dtype: int64

In [90]:
columns = ['Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Price', 'Content Rating', 'Genres']

df = raw_df[columns]
df

,Category,Rating,Reviews,Size,Installs,Price,Content Rating,Genres
0,ART_AND_DESIGN,4.1,159,19M,"10,000+",0,Everyone,Art & Design
1,ART_AND_DESIGN,3.9,967,14M,"500,000+",0,Everyone,Art & Design;Pretend Play
2,ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",0,Everyone,Art & Design
3,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",0,Teen,Art & Design
4,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",0,Everyone,Art & Design;Creativity
...,...,...,...,...,...,...,...,...
10836,FAMILY,4.5,38,53M,"5,000+",0,Everyone,Education
10837,FAMILY,5.0,4,3.6M,100+,0,Everyone,Education
10838,MEDICAL,NaN,3,9.5M,"1,000+",0,Everyone,Medical
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",0,Mature 17+,Books & Reference
10840,LIFESTYLE,4.5,398307,19M,"10,000,000+",0,Everyone,Lifestyle